defaults:
  - model: DecisionTreeRegressor
  - hpo: optuna
  - _self_

seed: 42

data:
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"

mlflow:
  experiment_name: "House-Rent-Optimization"
  registered_model_name: "HouseRent_Best"

hydra:
  run:
    dir: .
  output_subdir: null